version: 1.0.{build}
build_script:
- cmd: echo "test build..."
test: off
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
