version: 1.0.{build}

build_script:

- cmd: echo "test build..."

test: off

skip_commits:

	# Regex for matching commit message

	message: /\(doc\).*/

on_finish:

- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
